<?php require_once __DIR__.'/cabinet/lib.php'; $L=cab_cfg()['legal'];
echo cab_page('Контакты и реквизиты');
echo '<div class="card">';
echo '<h1 style="font-size:20px;margin-top:0">Контакты и реквизиты</h1>';
echo '<p><b>'.cab_h($L['name']).'</b></p>';
echo '<ul style="list-style:none;padding:0;line-height:1.9">';
echo '<li>ИНН: '.cab_h($L['inn']).'</li>';
echo '<li>ОГРН: '.cab_h($L['ogrn']).'</li>';
echo '<li>Адрес: '.cab_h($L['address']).'</li>';
echo '<li>Телефон: '.cab_h($L['phone']).'</li>';
echo '<li>Email: <a href="mailto:'.cab_h($L['email']).'">'.cab_h($L['email']).'</a></li>';
echo '</ul>';
echo '<p class="muted"><a href="/">← На главную</a></p>';
echo '</div>';
echo cab_page_end(false);
